### PR TITLE
hello-microverse 

### PR DESCRIPTION
**Pull request by zakiyousufi**
### In this pull request I have worked on my first project in microverse that has these requirements:

- I created a new GitHub repo.
- I created a new branch according to the GitHub flow rules 
- I added a .gitignore file.
- I set up a linter for HTML and CSS
- I added a descriptive README file to my project 
- I added an html file that includes a header with the text "Hello Microverse!". 
  - and a css style tag that includes one class with styles for your header 
- also added a test.md file with the text "This file should be ignored by git".
  - then added it to  .gitignore file

### CODE REVIEW

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi @zakiyousufi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly be noticed that the Linter result should be green. AKA: Linter should report NO errors.
- [ ] Kindly be noticed that there are 2 files that should be committed: an .html and .css file.
- [ ] Kindly be noticed that the .gitignore file should be listing `test.md` file and `node_modules` directory.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by OmarRamoun — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @zakiyousufi 👋

Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get Approved ✔️! in microverse 🌐.

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ no linter errors
- ✔️ descriptive commit messages
- ✔️ good communication in PR

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [@omarramoun](https://github.com/omarramoun)
- This is My **Twitter**: [@omarramoun](https://twitter.com/omarramoun)
- This is My **Slack**: [Ramoun](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zakiyousufi** [comment]
@OmarRamoun 
Thank you very much for your help and helpful feedbacks 😊

**Comment by OmarRamoun** [comment]
No worries, @zakiyousufi. Have nice day and Happy Hacking 👍

**Pull request merged**
